name: shop
description: The shop project
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Anotation for models
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.2
  # State manager
  flutter_bloc: ^8.1.1
  # Unit tests
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  # Custom route in app
  auto_route: ^5.0.1
  # Http client for app
  dio: ^4.0.6
  injectable: ^1.5.3
  fpdart: ^0.2.0
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Handle Image from internet.
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  # Injectable generator
  injectable_generator: ^1.5.4
  # Route generator
  auto_route_generator: ^5.0.2
  # DataBase generator
  hive_generator: ^1.1.3
  # Linter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
